// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dewqnvzxzejqbfstubum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRld3Fudnp4emVqcWJmc3R1YnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDYzNzQsImV4cCI6MjA1NDY4MjM3NH0.EXqSmxNEK2cXNwO6XUuPzVzUTGBNE4yw_i_wu_eDspA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);